name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/note-app:latest .
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/note-app:latest

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install iximiuz Labs CLI
      run: |
        curl -sf https://labs.iximiuz.com/cli/install.sh | sh
        # Add the installation directory to PATH
        echo "export PATH=$PATH:/home/runner/.iximiuz/labctl/bin" >> $GITHUB_ENV
        # Verify the CLI is installed
        labctl --version

    - name: Deploy to server
      run: |
        iximiuz ssh ${{ secrets.SERVER_IP }} -u ${{ secrets.SERVER_USER }} -k ${{ secrets.SSH_PRIVATE_KEY }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
          docker stop note-app-container || true
          docker rm note-app-container || true
          docker run -d -p 80:80 --name note-app-container ${{ secrets.DOCKER_USERNAME }}/note-app:latest
        EOF
      

  
