name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/note-app:latest .
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/note-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa

    - name: SSH into VM and Deploy Docker image
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i /tmp/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}
        docker pull ${{ secrets.DOCKER_USERNAME }}/note-app:latest &&
        docker stop my-container || true &&
        docker rm my-container || true &&
        docker run -d --name my-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/note-app:latest
      

  
